### PR TITLE
Add scrollbar for long text if necessary, closes #193

### LINKED ISSUE #193: The horizontal scroll should be on the console
As per following gif, now it just shows below the current (long) evaluated result/input.

recording_2016-04-05_114445

### PR DESCRIPTION
**Pull request by tomasz-biernacki**
Wrap the items as in the gif below:
yoelid69u9

### CODE REVIEW

**Comment by arichiardi** [comment]
Hey @tomasz-biernacki there is no way to add the scrollbar to the window right? Wrapping is good but what if I have a very big output? I would still like to see it but without cluttering the little console window.
Just asking, but I would make the wrapping optional.

**Comment by tomasz-biernacki** [comment]
I guess you can have the scroll bar ;)
Will try and see what is looking better.

**Comment by arichiardi** [comment]
Just a proposal for better UX :dancer:

**Comment by tomasz-biernacki** [comment]
:+1:

**Pull request merged**
