### PR TITLE
popup-tour 

### PR DESCRIPTION
**Pull request by dstiberova**
**Parts of the popup-tour are for now:**
* Start tour button
* Reset
* Clear
* Create gist
* Clear examples
* Switch input mode
* Console

eplumb repl20160427183817

Questions: 
* What else should be the part of the tour? 
* We need to think about texts for the tour. 
* We need to change the design of the pop-up tour to match the rest of the site (maybe design of the whole page as we were talking).

@tomasz-biernacki @arichiardi

### CODE REVIEW

**Comment by arichiardi** [comment]
A few notes:

* we can add a tour on one of the buttons below and the "Send to REPL" button as well
* the Start Tour button should not exist, we launch it the first time (if there is no `:first-launch` in local storage) and we ask the user if he/she wants to skip it

**Comment by dstiberova** [comment]
@arichiardi you mean pop-up in pop-up? because send-in-repl is in pop-up. So if I understood it right, tour should open the pop-up (first function) and show the tour pop-up in this pop-up? :)

I can launch the tour when user open the website, but it will be visible every time user opens the website as we don't have cookies. 
And in my opinion is good to have start tour button on the website because user can start in at any time when he needs it.

**Comment by arichiardi** [comment]
@dstiberova we have local storage not cookies, have a look at [this](https://github.com/Lambda-X/cljs-repl-web/blob/devel/src/cljs/cljs_repl_web/localstorage.cljs). So you can save a `:first-launch` boolean there and you don't need any button.

About th popup of a popup, I don't know if we can do it but I would like to.

**Comment by dstiberova** [comment]
@arichiardi Start button removed so the tour run when the user goes on the website for the first time, but I'll need a little help from @tomasz-biernacki with the popup on first item bellow and with the pop-up on the pop-up.

**Comment by arichiardi** [comment]
So what is the issue exactly?

**Comment by tomasz-biernacki** [comment]
I will write it here so I don't forget; **things to mention**:
- buttons: 
  - reset -> clears screen _and_ history
  - clear -> clear screen only
  - gist -> creates gist
  - stop interactive examples -> clears forms and current line
  - switch input mode -> explain about the modes + link to parinfer repo
- editor
  - UP/DOWN -> history
  - SHIFT-ENTER -> newline
  - click on history item -> puts it in current line
- example -> show SEND TO REPL

**Pull request merged**
